import React from 'react';
import {
    Button,
    createStyles,
    Dialog,
    DialogActions,
    DialogContent,
    DialogContentText,
    DialogTitle,
    TextField,
    Theme,
    WithStyles,
    withStyles
} from "@material-ui/core";
import Constants from "../constants";

interface ExportDialogProps extends WithStyles<typeof appStyles> {
    open: boolean,
    onClose: () => void,
    text: string
}

const appStyles = (theme: Theme) => createStyles({
    theInput: {
        fontSize: 10,
        fontFamily: 'Courier'
    }
});

export default withStyles(appStyles)(
    class extends React.Component<ExportDialogProps, any> {

        constructor(props: ExportDialogProps) {
            super(props);
        }

        private handleClose = () => {
            this.props.onClose();
        };

        render() {
            return (
                <div>
                    <Dialog open={this.props.open} onClose={this.handleClose} aria-labelledby="form-dialog-title" maxWidth="md" fullWidth={true}>
                        <DialogTitle id="form-dialog-title">Export Diagram</DialogTitle>
                        <DialogContent>
                            <DialogContentText>
                                Here is the diagram markup generated by our really nice editor:
                            </DialogContentText>
                            <TextField
                                InputProps={{
                                    className: this.props.classes.theInput
                                }}
                                autoFocus
                                margin="dense"
                                id="name"
                                label="Diagram Markup"
                                type="text"
                                fullWidth
                                multiline
                                rows={Constants.numberOfRows}
                                defaultValue={this.props.text}
                            />
                        </DialogContent>
                        <DialogActions>
                            <Button onClick={this.handleClose} color="primary">
                                Close
                            </Button>
                        </DialogActions>
                    </Dialog>
                </div>
            );
        }
    });
